### ISSUE TITLE
Office theme and PHP 8.1 incompatibility

### ISSUE THREAD

**Issue by wondrack** [wpexplorer/office#3]
Hi, I have a client that is still using your Office WP theme.
My host, Dreamhost, is sunsetting support for old PHP versions and the theme and my client's site unsupported as of May. 
They are recommending all sites update to PHP 8.1 and currently when I run the update, I receive the following error:

/usr/bin/wp: line 23: cd: /root: Permission denied PHP Fatal error: Uncaught Error: Call to undefined function create_function() in /home/wondrack/LinchpinStrategy.com/wp-content/themes/Office/functions/widgets/flickr-widget.php:83 Stack trace: #0 /home/wondrack/LinchpinStrategy.com/wp-content/themes/Office/functions.php(985): require_once() #1 /home/wondrack/LinchpinStrategy.com/wp-settings.php(585): include('/home/wondrack/...') #2 /usr/local/wp/php/WP_CLI/Runner.php(1319): require('/home/wondrack/...') #3 /usr/local/wp/php/WP_CLI/Runner.php(1237): WP_CLI\Runner->load_wordpress() #4 /usr/local/wp/php/WP_CLI/Bootstrap/LaunchRunner.php(28): WP_CLI\Runner->start() #5 /usr/local/wp/php/bootstrap.php(78): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState)) #6 /usr

Appreciate any help with updating Office to be compatible. 
Thanks
James

**Comment by wpexplorer** [comment]
Hi James, these issues have already been fixed in the current version here on Github: https://github.com/wpexplorer/office/releases/tag/v2.9.0
